version: '3.8'

services:
  mysql-expense:
    image: mysql:8.0
    container_name: mysql-expense
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: expensedb
      MYSQL_USER: expenseuser
      MYSQL_PASSWORD: expensepass
    volumes:
      - mysql-expense-data:/var/lib/mysql
volumes:
  mysql-expense-data: