version: '3.8'

services:
  mysql-auth:
    image: mysql:8.0
    container_name: mysql-auth
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: authdb
      MYSQL_USER: authuser
      MYSQL_PASSWORD: authpass
    volumes:
      - mysql-auth-data:/var/lib/mysql

  redis:
    image: redis:7.0
    container_name: redis-auth
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    # Optional: Set Redis password
    # command: redis-server --requirepass yourpassword

volumes:
  mysql-auth-data:
  redis-data: